### ISSUE TITLE
Add support for custom texmf folder

### ISSUE THREAD

**Issue by mtneug** [mtneug/texlive-docker#2]

**Comment by hfjn** [comment]
## Todo:

- [ ] Maybe we should add/modify a test document with a texmf tree and a font?
- [ ] `--map` instead of `--init`
- [ ] Export `TEXMFHOME` in `main`
- [ ] `mtexlsr` -> `mktexlsr` 😉
- [ ] Call `mktexlsr`automatically when needed.

For further explanations see #3.
